routes/web.php
<?php

use App\Http\Controllers\ActualiteController;
use App\Http\Controllers\AxesController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\GalerieController;
use App\Http\Controllers\ParametreController;
use App\Models\Axes;
use App\Models\Galerie;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/about', function () {
    return view('about');
});

/**
 * Auth Routes
 */
Auth::routes(['verify' => false]);


Route::group(['namespace' => 'App\Http\Controllers'], function()
{
    Route::middleware('auth')->group(function () {
        /**
         * Home Routes
         */
        Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
        /**
         * Role Routes
         */
        Route::resource('roles', RolesController::class);
        /**
         * Permission Routes
         */
        Route::resource('permissions', PermissionsController::class);
        /**
         * User Routes
         */
        Route::group(['prefix' => 'users'], function() {
            Route::get('/', [App\Http\Controllers\UsersController::class, 'index'])->name('users.index');
            Route::get('/create', 'UsersController@create')->name('users.create');
            Route::post('/create', 'UsersController@store')->name('users.store');
            Route::get('/{user}/show', 'UsersController@show')->name('users.show');
            Route::get('/{user}/edit', 'UsersController@edit')->name('users.edit');
            Route::patch('/{user}/update', 'UsersController@update')->name('users.update');
            Route::delete('/{user}/delete', 'UsersController@destroy')->name('users.destroy');
        });
    });
});

//Admin
Route::resource('/Axes',  AxesController::class);
Route::resource('/Client',  ClientController::class);
Route::resource('/Parametre',  ParametreController::class);
Route::resource('/actualite',  ActualiteController::class);
Route::resource('/galery',  GalerieController::class);













//User


Route::get('/', [App\Http\Controllers\AxesController::class,'indexuser'])->name('axes.list');
Route::get('/nosDomaines', [App\Http\Controllers\AxesController::class,'nosDomaines'])->name('nosDomaines');
Route::get('/catalogue', [App\Http\Controllers\AxesController::class,'catalogue'])->name('catalogue');
Route::get('/actualites', [App\Http\Controllers\ActualiteController::class,'Actualite'])->name('actualites.index');
Route::get('/actualites/{id}', [ActualiteController::class, 'detail']);
Route::get('/calendriers', [App\Http\Controllers\ActualiteController::class,'calendriers'])->name('calendriers.index');
//Route::get('/', [App\Http\Controllers\ClientController::class,'indexuser'])->name('client.list');

app/Models/Actualite.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\Pivot;

class Actualite extends Pivot
{
    use HasFactory;
    protected $table ='actualite';
    protected $guarded = [];
    public $timestamps = true;
}

app/Http/Controllers/ActualiteController.php
<?php

namespace App\Http\Controllers;

use App\Models\Actualite;
use App\Models\Axes;
use App\Models\Parametre;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Database\Eloquent\Builder;

class ActualiteController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {

        $actualite = Actualite::all();
        return view("Actualite.list", compact("actualite"));
    }

    public function Actualite(Request $request)
    {
        $parametre = Parametre::all();
        $axes = Axes::all();
        $actualite = Actualite::query()
            ->when(
                $request->q,
                function (Builder $builder) use ($request) {
                    $builder->where('titre_actualite', 'like', "%{$request->q}%")
                        ->orWhere('prof', 'like', "%{$request->q}%")
                        ->orwhere('axe_id', 'like', "%{$request->qf}%");
                }
            )
            ->simplePaginate(1);
            //dd($actualite);

        return view("pageuser.Actualite.index", compact("actualite", 'parametre','axes'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $actualite = Actualite::all();
        $axes = Axes::all();
    return view("Actualite.create", compact("actualite", "axes"));
    }

    public function calendriers()
    {
        $actualite = Actualite::all();
        $axes = Axes::all();
    return view("pageuser.calendrier.index", compact("actualite", "axes"));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request): RedirectResponse
    {
        $file = time() .".". $request->file("image_actualite")->extension();
        $path = $request->file('image_actualite')->storeAs(
            'image_actualite',
            $file,
            'public',
        );
        // $request->validate([
        //     'description_axes'=> 'required',
        //     'nom_axes'=> 'required',
        // ]);
        //$request->image_axes = $name;

        //dd($request->all());
        $post = Actualite::create(
            [
                'calendrier'=> $request->calendrier,
                'axe_id'=> $request->axe_id,
                'prof'=> $request->prof,
                'titre_actualite'=> $request->titre_actualite,
                'Lieu'=> $request->Lieu,
                'datedebut'=> $request->datedebut,
                'heuredebut'=> $request->heuredebut,
                'datefin'=> $request->datefin,
                'heurefin'=> $request->heurefin,
                'mini_description'=> $request->mini_description,
                'description_actualite'=> $request->description_actualite,
                'Home'=> $request->Home,
                'Archive'=> $request->Archive,
                'image_actualite' => $path,
            ]
        );

        $axes =new Actualite();
        $axes->path = $path;
        //$post->axes()->save($axes);

        session()->flash('success', 'Actualite Creer successfully');
        return redirect()->route('actualite.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Actualite $actualite): Response
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Actualite $actualite): Response
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Actualite $actualite): RedirectResponse
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $Axes = Actualite::find($id);
        $Axes->delete();
        session()->flash('success','Actualite supprimer Avec success');
            return redirect()->route('actualite.index');
    }


    public function detail($id)
    {
        //dd($id);
        $parametre = parametre::all();
        $actualite = Actualite::where('id', $id)->get();
        $axes = Axes::All();


        //dd($essai);
        //dd($actualite);
        return view('pageuser.Actualite.detail', compact('actualite', 'parametre','axes'));
    }
}

resources/views/Actualite/create.blade.php
@extends('layouts.app')

@section('title')
Create Etudiant
@endsection

@section('content')
<div class="bg-light rounded">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Ajouter Nouvelle Actualite</h5>
            <div class="p-4 rounded">
                <div class="container mt-4">



                    <form method="POST" action="{{route('actualite.store')}}" enctype="multipart/form-data">
                        @csrf
                        <div class="container">
                            <div class="row">
                              <div class="col">
                                <label class="block mb-4">
                                    <span class="sr-only">Choose File</span>
                                    <input type="file" name="image_actualite"/>
                                    @error('image')
                                    <span class="text-red-600 text-sm">{{ $message }}</span>
                                    @enderror
                                </label>
                                <div class="mb-1">
                                    <div class="col-md">
                                        <div class="form-floating">
                                          <select class="form-select" id="floatingSelectGrid" aria-label="Floating label select example" name="axe_id">
                                            <option selected>Choisir Une formation</option>
                                            @foreach ($axes as $items)
                                            <option value=" {{$items->id}} ">{{$items->nom_axes}}</option>
                                            @endforeach

                                          </select>
                                          <label for="floatingSelectGrid">Formation</label>
                                        </div>
                                      </div>
                                </div>
                                <div class="mb-1 ">
                                    <label for="titre_actualite" class="form-label">Titre</label>
                                    <input value="{{ old('titre_actualite') }}" type="text" class="form-control" name="titre_actualite"
                                        required>
                                </div>
                                <div class="mb-1">
                                    <label for="nom_niveau" class="form-label">Mini Description</label>
                                    <textarea value="{{ old('nom_axes') }}"class="form-control" name="mini_description"style="height: 50px"
                                        required></textarea>
                                </div>
                                <div class="mb-1">
                                    <label for="nom_niveau" class="form-label">Description</label>
                                    <textarea value="{{ old('nom_axes') }}"class="form-control" name="description_actualite"style="height: 100px"
                                        required></textarea>
                                </div>

                                <div class="mb-1 ">
                                    <label for="nom_niveau" class="form-label">Professeur</label>
                                    <input value="{{ old('professeur') }}" type="text" class="form-control" name="prof"
                                        required>
                                </div>
                                <div class="mb-1 ">
                                    <label for="datedebut" class="form-label">Date Debut</label>
                                    <input value="{{ old('datedebut') }}" type="date" class="form-control" name="datedebut"
                                        required>
                                </div>
                                <div class="mb-1 ">
                                    <label for="heuredebut" class="form-label">Heure Debut</label>
                                    <input value="{{ old('heuredebut') }}" type="time" class="form-control" name="heuredebut"
                                        required>
                                </div>


                                <div class="mb-1 ">
                                    <label for="datefin" class="form-label">Date Fin</label>
                                    <input value="{{ old('datefin') }}" type="date" class="form-control" name="datefin"
                                        required>
                                </div>
                                <div class="mb-1 ">
                                    <label for="heurefin" class="form-label">Heure Fin</label>
                                    <input value="{{ old('heurefin') }}" type="time" class="form-control" name="heurefin"
                                        required>
                                </div>

                                <div class="m-lg-3">
                                <div class="checkbox">
                                    <label>
                                      <input type="checkbox" data-toggle="toggle" class="form-control" name="Home">
                                      Affiche Sur le menu
                                    </label>
                                  </div>
                                  <br/>

                                  <div class="checkbox">
                                    <label>
                                      <input type="checkbox" data-toggle="toggle" class="form-control" name="Archive">
                                      Archiver
                                    </label>
                                  </div>
                                  <br>
                                  <div class="checkbox">
                                    <label>
                                      <input type="checkbox" data-toggle="toggle" class="form-control" name="calendrier">
                                      calendrier
                                    </label>
                                  </div>
                                </div>

                                {{-- <div class="mb-1">
                                    <div class="input-group-prepend">
                                      <select class="form-select" id="floatingSelectGrid" aria-label="Floating label select example"id="isActive" name="isActif">
                                        <option selected>Choose...</option>
                                        <option value='Activer'> Activer</option>
                                        <option value='Desactiver'> Desactiver</option>
                                      </select>
                                    </div>
                                </div> --}}
                              </div>
                            </div>
                          </div>

                        <button type="submit" class="btn btn-primary">Enregistrer Niveau</button>
                        <a href="{{ route('actualite.index') }}" class="btn btn-default">Back</a>
                    </form>
                </div>

            </div>
        </div>
    </div>

    @endsection

resources/views/Actualite/edit.blade.php
@extends('layouts.app')

@section('title')
    Modiifier Etudiant
@endsection

@section('content')
    <div class="bg-light rounded">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Modifier Axe</h5>
                <div class="p-4 rounded">
                    <div class="container mt-4">



                        <form method="POST" action="{{ route('Axes.update', $Axes->id) }}">

                            @csrf
                            @method('PUT')
                            <div class="container">
                                <div class="row">
                                    <div class="col">
                                        <div class="mb-1">
                                            <label for="nom_niveau" class="form-label">Nom</label>
                                            <input value="{{ $Axes->nom_axes }}" type="text" class="form-control"
                                                name="nom_axes">
                                        </div>
                                        <div class="mb-1">
                                            <label for="nom_niveau" class="form-label">Description</label>
                                            <input value="{{ $Axes->description_axes }}" type="text" class="form-control"
                                                name="nom_axes">
                                        </div>
                                        <div class="input-group-prepend">
                                            <select class="custom-select" id="isActive" name="isActif">
                                                @if ($Axes->isActif == 'isActif')
                                                    <option selected>{{ $Axes->isActif }}</option>
                                                    <option value='Desactiver'> Desactiver</option>
                                                @else
                                                    <option selected>{{ $Axes->isActif }}</option>
                                                    <option value='Activer'> Activer</option>
                                                @endif
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <button type="submit" class="btn btn-primary">Modifier Niveau</button>
                            <a href="{{ route('Axes.index') }}" class="btn btn-default">Back</a>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    @endsection

resources/views/Actualite/list.blade.php
@extends('layouts.app')

@section('title')
Actualite List
@endsection

@section('content')

<div class="bg-light rounded">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Actualite</h5>
            <h6 class="card-subtitle mb-2 text-muted">Gerer vos Actualite</h6>

            <div class="mt-2">
                @include('layouts.includes.messages')
            </div>
            <div class="mb-2 text-end">
                <a href="{{ route('actualite.create') }}" class="btn btn-info btn-loading" data-coreui-toggle="loading-button ">Ajouter Actualité</a>
            </div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col" width="1%">#</tpermissionh>
                        <th scope="col" width="15%">Image</th>
                        <th scope="col" width="15%">Titre</th>
                        <th scope="col" width="15%">Mini Description</th>
                        <th scope="col" width="15%">Home</th>
                        <th scope="col" width="15%">Archivre</th>
                        <th scope="col" width="15%">Calendrier</th>
                        <th width="3%" colspan="3">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($actualite as $items)
                    <tr>
                        <th scope="row">{{ $items->id }}</th>
                        <td> <img src="{{Storage::url($items->image_actualite)}}" width="50" height="60"></td>
                        <td>{{ $items->titre_actualite }}</td>
                        <td>{{ $items->mini_description }}</td>
                        <td>
                            @if ($items->Home = 'on')
                                <span>Activer</span>
                                @else
                                <span>Desactiver</span>
                            @endif
                        </td>
                        <td>
                            @if ($items->Archive = 'on')
                                <span>Activer</span>
                                @else
                                <span>Desactiver</span>
                            @endif
                        </td>
                        <td>
                            @if ($items->calendrier = 'on')
                                <span>Activer</span>
                                @else
                                <span>Desactiver</span>
                            @endif
                        </td>
                        <th scope="row">{{ $items->isActif }}</th>
                        <td><a href="{{ route('actualite.show', $items->id) }}" class="btn btn-warning btn-sm">Show</a></td>
                        <td><a href="{{ route('actualite.edit', $items->id) }}" class="btn btn-info btn-sm">Edit</a></td>
                        <td>
                            {!! Form::open(['method' => 'DELETE','route' => ['actualite.destroy',
                            $items->id],'style'=>'display:inline']) !!}
                            {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-sm']) !!}
                            {!! Form::close() !!}
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>

            <div class="d-flex">
                {{-- {!! $users->links() !!} --}}
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/Actualite/show.blade.php
@extends('layouts.app')

@section('title')
Show niveau
@endsection

@section('content')
<div class="bg-light rounded">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Show user</h5>

            <div class="container mt-4">
                <div>
                    Name: {{ $niveau->nom_niveau }}
                </div>
                <div class="mt-4">
                    {{-- <a href="{{ route('etudiant.edit') }}" class="btn btn-info">Edit</a> --}}
                    <a href="{{ route('niveau.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>

        </div>

    </div>
</div>
@endsection